runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /convert.*
  script: main.application
  secure: always

- url: /parse
  script: main.application
  secure: always

- url: /
  static_files: index.html
  upload: index\.html
  secure: always

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  secure: always

- url: /humans\.txt
  static_files: humans.txt
  upload: humans\.txt
  secure: always
